### ISSUE TITLE
Importação variável V0015

### ISSUE THREAD

**Issue by gdocesp** [Gabriel-Assuncao/PNSIBGE#2]
Olá, gostaria de trabalhar com a variável V0015, que estão presentes no arquivo de microdados, mas quando utilizo a função pns_desgin estas observações desaparem. Tanto que o total da amostra diminui.

Já com a importação online os dados amostrais baixados também já excluem as obervações com respostas diferentes de "Realizada".

Tem alguma forma de trabalhar com estes dados e seus respectivos pesos para construção de amostra complexa?

**Comment by Gabriel-Assuncao** [comment]
Bom dia.

Então, na realidade para que possamos realizar o processo de incorporação do desenho amostral corretamente é necessária a exclusão de todas as observações em que não houve entrevista realizada, já que no peso ou fator de expansão da amostra já existe o processo de correção da não-resposta, em que justamente corrigimos os pesos por conta das entrevistas não realizadas.

Através do pacote é possível realizar a adaptação da função read_pns, sugerimos a criação de uma nova função com outro nome, como por exemplo read_pns_alterated, onde basta a remoção ou inserção da instância de comentário na linha 'data_pns <- data_pns[(data_pns$V0015 == "01" & !is.na(data_pns$V0015)),]' e caso necessite de utilizar o processo de obtenção dos microdados de forma online, também é preciso realizar a adaptação da função get_pns, também com a mesma sugestão de um novo nome como get_pns_alterated, onde basta trocar a linha 'data_pns <- PNSIBGE::read_pns(microdata=microdatafile, input_txt=inputfile, vars=vars)' por 'data_pns <- read_pns_alterated(microdata=microdatafile, input_txt=inputfile, vars=vars)'.

No entanto, caso deseje realizar o processo de incorporação do desenho amostral nesta nova adaptação, será indicado erro, justamente pelas observações onde a entrevista não foi realizada apresentarem NAs para as variáveis utilizadas no processo de incorporação do desenho amostral, por isso indicamos que para trabalhar com os microdados neste novo formato mantenha o argumento design da função get_pns como FALSE, ou seja, as análises deverão ser realizadas nos microdados coletados em nível de amostra e não expandidos a nível populacional.

Qualquer dúvida ou solicitação que surgir, indicamos por gentileza que entre através do canal de atendimento pacotesipd@ibge.gov.br para que possamos realizar seu atendimento com as informações necessárias.

Esperamos que as informações acima possam ser suficientes para sanar as dúvidas apresentadas, no entanto caso ainda haja alguma pendência, pedimos por gentileza que entre em contato novamente.

**Comment by gdocesp** [comment]
Obrigado!
