### ISSUE TITLE
Hipertensão arterial - PNS 2019

### ISSUE THREAD

**Issue by antunesab** [Gabriel-Assuncao/PNSIBGE#3]
Olá! 

Estou utilizando o pacote PNSIBGE para calcular a prevalência de hipertensão arterial referida. No entanto, não estou conseguindo alcançar a mesma estimativa do relatório publicado. Segue abaixo o código que estou utilizando: 

`###Morador selecionado####
vars <- c("V0026","C006","V0001","C009", "VDF004", "VDD004A", "V0031","V00281", 
          "Q00202", "Q00201","Q03002", "Q03001", "Q028","Q058","Q06306")
design <- get_pns(year=2019,design=TRUE, selected = TRUE, vars=vars)
dados <- get_pns(year=2019,design=FALSE, selected= TRUE, vars=vars)

######################################Módulo Q###################################
#Diagnóstico autorreferido de Hipertensão arterial 
dados = dados %>% mutate(Q002P = if_else(Q00202=="Sim" & C006=="Mulher","Não",
                                         if_else(Q00201=="Sim","Sim","Não",missing="Não"),missing="Não"))
HA <- svymean(x=~dados$Q002P, design=design, na.rm=TRUE)
confint(HA)`

Para criação da variável Q002P utilizei os mesmo filtros do script disponível no painel da ICICT (https://www.pns.icict.fiocruz.br/calculo-dos-indicadores-modulo-q-2019/). 

Poderia me auxiliar se estou fazendo algo errado. 
Obrigada desde já.

**Comment by Gabriel-Assuncao** [comment]
Prezado @antunesab, boa tarde.

Na realidade, o mais adequado a ser realizado para obtenção da estimativa desejada é a utilização de somente um objeto já com o desenho amostral devidamente incorporado, ou seja, sem a criação de dois objetos, onde a manipulação é feita em um e o outro é utilizado para obtenção dos resultados.

Assim, para correta obtenção da estimativa, de fato é necessário realizar o tratamento de NAs para as variáveis Q00201 e Q00202, e para isso basta utilizar a função transform diretamente no objeto já com o desenho amostral incorporado.

Além disso, ao obter a estimativa utilizando as funções do pacote survey, para que consiga chegar ao resultado desejado é preciso fazer um recorte para pessoas de 18 anos ou mais de idade utilizando a função subset.

Abaixo estarei fornecendo um código de exemplo para obtenção da estimativa desejada, em valor total e percentual tomando como referência a [tabela 4418 do SIDRA](https://sidra.ibge.gov.br/tabela/4418):

library("PNSIBGE")
library("survey")
variaveis_selecionadas <- c("V0026","C006","C008","V0001","C009","VDF004","VDD004A","V0031","V00281","Q00202","Q00201","Q03002","Q03001","Q028","Q058","Q06306")
pns2019_moradorselecionado <- get_pns(year=2019, selected=TRUE, vars=variaveis_selecionadas)
pns2019_moradorselecionado$variables <- transform(pns2019_moradorselecionado$variables, Brasil=as.factor("Brasil"))
pns2019_moradorselecionado$variables <- transform(pns2019_moradorselecionado$variables, GR=as.factor(ifelse(substr(x=UPA_PNS,start=1,stop=1)=="1","Norte",ifelse(substr(x=UPA_PNS,start=1,stop=1)=="2","Nordeste",ifelse(substr(x=UPA_PNS,start=1,stop=1)=="3","Sudeste",ifelse(substr(x=UPA_PNS,start=1,stop=1)=="4","Sul",ifelse(substr(x=UPA_PNS,start=1,stop=1)=="5","Centro-oeste",NA)))))))
pns2019_moradorselecionado$variables$GR <- factor(pns2019_moradorselecionado$variables$GR, levels=c("Norte","Nordeste","Sudeste","Sul","Centro-oeste"))
pns2019_moradorselecionado$variables <- transform(pns2019_moradorselecionado$variables, MQ00201=as.factor(ifelse(is.na(Q00201),"Não aplicável",as.character(Q00201))))
pns2019_moradorselecionado$variables <- transform(pns2019_moradorselecionado$variables, MQ00202=as.factor(ifelse(is.na(Q00202),"Não aplicável",as.character(Q00202))))
print(x=total_hipertensao <- svybys(formula=~as.integer(MQ00201=="Sim" & MQ00202!="Sim"), bys=~Brasil+GR, design=subset(pns2019_moradorselecionado, C008>=18 & C008<999), FUN=svytotal, keep.names=FALSE, vartype=c("se","cv"), na.rm=TRUE))
print(x=percentual_hipertensao <- svybys(formula=~as.integer(MQ00201=="Sim" & MQ00202!="Sim"), bys=~Brasil+GR, design=subset(pns2019_moradorselecionado, C008>=18 & C008<999), FUN=svymean, keep.names=FALSE, vartype=c("se","cv"), na.rm=TRUE))

Diante disso, estarei fechando esta issue, daí qualquer dúvida ou problema que surgir, peço por gentileza que entre em contato diretamente como o canal de atendimento pacotesipd@ibge.gov.br.

Sendo assim, agradeço imensamente pela atenção e me coloco à disposição para qualquer eventualidade.

Atenciosamente,
Gabriel Henrique Oliveira Assunção.
